- build/action.yml
- publish/action.yml
- release/action.yml
Add this URL in the env file as it's the one used to access artifacts in staging. So it's required when you want to build an artifact depending on another located in a staging repository
> Add the Nexus internal url variable to the env file

- sonar-analysis/action.yml
Some modules require access to Nexus for some of the analysis
> TECH-547: Added nexus credentials to sonar action

- update-signature/action.yml
https://jira.jahia.org/browse/TECH-811
From the ticket, `keymaker/cli` artifacts has been moved to nexus internal repository and needs to be reflected in the update-signature action.
Use a default value to fix issue for all modules.
* `NEXUS_INTERNAL_RELEASES_URL` has been set to `https://devtools.jahia.com/nexus/content/repositories/jahia-internal-releases` (https://support.jahia.com/browse/INFRA-2276)
* Note that this value has been hardcoded as we can't refer to secrets within an action. Will need to do some clean-up after https://jira.jahia.org/browse/TECH-827
* curl url has been updated to https://devtools.jahia.com/nexus/content/repositories/jahia-internal-releases/org/jahia/keymaker/keymaker-cli/2.0/keymaker-cli-2.0-jar-with-dependencies.jar
This change will give a warning when run …
> TECH-811: Update use of NEXUS_INTERNAL_RELEASES_URL for update signature action

- build/action.yml
The debug "feature" was previously only present in the integration tests, adding it to the code-sign workflow since we're having issues there.
> Added debug feature

- sonar-analysis/action.yml
Github uses `/refs/heads/BRANCH_NAME` when referring to the branch. To clean things in Sonarqube, it was necessary to remove `/refs/heads/`.
> Remove refs from branch name

- update-signature/action.yml
There was a failure on this release: https://github.com/Jahia/jexperience/runs/7741440672?check_suite_focus=true because this 7x module does not have a signature, thus there's nothing to commit, which fails the CI.
This PR checks if there are staged changes, and only then, performs a commit.
> Handle situations where there's no signature updated

- docker-tags/action.yml
There was an error when porting over the action from CircleCI, with GitHub Action "export" is not needed to define environment variables.
> BACKLOG-19964: Fixed incorrect way of setting up environment variable

- docker-tags/action.yml
There was an issue in which a the tag action was trying to alias an image built from a branch
> BACKLOG-19964: Added a filter before triggering the push

- static-analysis/action.yml
This was introduced recently, this option aims at caching the dependencies (I guess for in-between jobs), since all steps are executed in the same job, this shouldn't be necessary.
> Removing yarn which is not needed here

- build/action.yml
We had a dedicated upload step for uploading coverage results, but if you look at the step "Archive build artifacts", it is already uploading these reports if present, so that step is actually redundant (and I doubt it's used in repos).
> Removed unnecessary artifact upload

- build/action.yml
- publish/action.yml
That artifact is added to the "build-artifacts" archive being used by the integration tests during the on-code-change and on-merge workflows.
For nightly, it will remain necessary to update each repo's snapshot manifest, but that can be done alongside the introduction of the test module in the repo.
> TECH-1147: Added the handling for a test artifact to be built and usable in the integration tests

- release/action.yml
For running our tests with the test module on nightly (or manual) execution, we need to use the test artifacts stored in nexus.
If its version is not kept in-sync with the actual module it's testing, it can easily become painful to maintain. This PR adds the same logic than the publish action but adapted for release.
Note: The NPM modules are not covered.
Important: The pom.xml file of the test module must include the scm section, otherwise it will try pushing to a non-existing repo.
> Update release action to include test module

- dependencies-check-java/action.yml
https://jira.jahia.org/browse/TECH-1641
Fix a problem in the maven cache management during dependency check phase for jahia-core.
The bug only occurs when a new maven artefact is included in the core and used in another core part.
By the way the cause affect the whole cache usage in dependency check.
> TECH-1641: Dependency check fails because of artefact not found in maven repository

- static-analysis/action.yml
https://jira.jahia.org/browse/TECH-1635
- Two new inputs are added on the static-analysis action: yarn_version and yarn_tests_version
- If not specified the action will perform as before
- If specified they will be used like this : if [[ -n "${{ inputs.yarn_version }}" ]]; then yarn set version ${{ inputs.yarn_version }} fi
> TECH-1635 Make it possible to specify Yarn versions for static analysis action

- sbom-processing/action.yml
https://support.jahia.com/browse/INFRA-2967
Trying out the fix here: https://github.com/Jahia/remotepublish/actions/runs/10450275325
> INFRA-2967: Use fork for SBOM upload until ECONNRESET issue is fixed

- sbom-processing/action.yml
https://jira.jahia.org/browse/INFRA-2967
Switch to latest gh-upload-sbom release and remove temporary comments
> INFRA-2967: Switch to latest gh-upload-sbom release

- .github/workflows/integration-tests.yml
https://jira.jahia.org/browse/PIPELINE-81
There's one thing unknown for now is how to make this reusable workflow compatible with jExperience (due to additional jexp-specific env variables). But that can be dealt with later on, as it the workflow should work with most of our modules.
Here's a successful run using that workflow: https://github.com/Jahia/distributed-sessions/actions/runs/11276437536
> PIPELINE-81: Implement re-usable workflow for integration tests

- .github/workflows/integration-tests.yml
https://jira.jahia.org/browse/PIPELINE-81
Maven is used when building the test modules before docker build (part of jahia-cypress workflow).
I noticed the issue when porting the re-usable workflow on the graphql-core repo.
> PIPELINE-81: Added installation of maven

- build-step-npm/action.yml
- release-npm/action.yml
https://jira.jahia.org/browse/BACKLOG-23224
Use the `.jahia.snapshot` flag defined in the `package.json` file of our NPM modules to build and release.
In particular, when releasing a module, ensure the flag is disabled (as part of the "prepare release" commit) so the released artifact is not in snapshot mode, and re-renable the flag after releasing (as part of the "prepare for next development iteration" commit).
Also, fix the issue in the "SBOM processing" phase of the release workflow (see [this error in the release of luxe-jahia-demo:0.3.0](https://github.com/Jahia/luxe-jahia-demo/actions/runs/10384734159/job/28752445002)): delegate the build to `build-step-npm` that uploads the SBOM artifact, which can then be downloaded in the "SBOM processing" phase.
> BACKLOG-23224: Use .jahia.snapshot flag in package.json for NPM modules

- build-npm/action.yml
- build-step-npm/action.yml
https://jira.jahia.org/browse/BACKLOG-23333
Update the CI to get the .tgz file from the `dist/` folder since https://github.com/Jahia/javascript-components/pull/279.
In case there is no .tgz file in the `dist/` folder, fallback to the old behaviour to smoothly release this change. Eventually the _else_ condition should be removed once all Javascript projects use the "new" build tooling (that generates the file in the `dist/` folder).
Tested on Luxe in https://github.com/Jahia/luxe-jahia-demo/actions/runs/11743948367 (by forcing this branch to be used for the Github action).
> BACKLOG-23333: Move the .tgz to dist/ folder

- .github/workflows/issues-chores.yml
- Split by type of manipulation (attach to project, transfer, create links): I believe this improves maintainability and identifying what breaks if something happens to break. But the downside is that it will result in 3x checks in the Issue details (not necessarily a big issue)
- Attach Customers ticket to the customer board
> ci: cleanup of the issues chores workflow

- .github/workflows/issue-chores.yml
- .github/workflows/pr-chores.yml
The previous naming was confusing and could give the impression that the workflows were performing operations on multiple issues or multiple PRs
> Renamed chores workflows

- .github/workflows/delivery-issue-chores.yml
- delivery/check-issue-exists/action.yml
- delivery/delete-labels/action.yml
- Added context data to help debug run issues
- Added handling for the refresh label, useful if we need to trigger the issues workflow again
- Check if an issue exists before trying to create links in Jira. If the issue was moved it will not exist anymore.
> ci: Improved issue chores workflow robustness

- .github/workflows/delivery-issue-chores.yml
If a user decides to change an issue type, for example from Task to Epic, and if this issue has the right label, it might be necessary to add the issue to one of the projects.
> fix: updated the projects job to also capture change of issue type

- .github/workflows/reusable-delivery-issue-chores.yml
The previous action was first verifying credentials (GitHub and Jira) before trying to determine jira keys based on the content of the issue.
This new version only initiates the connection to Jira (first to verify credentials) once it confirmed jira keys are indeed present.
> chore: updated version of the create-jira-link action

- delivery/keep-issue-open/action.yml
This should prevent this from happening:
```
Run jahia/jahia-modules-action/delivery/keep-issue-open@v2
Run actions/github-script@v[7](https://github.com/Jahia/jexperience/actions/runs/12679913924/job/35340633257#step:3:8)
Issue with ID: PR_kwDOAT8V4s6HFz-V has status: undefined
TypeError: Cannot read properties of undefined (reading 'nodes')
at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35424:16), <anonymous>:55:46)
at async main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:35522:20)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'nodes')
```
https://github.com/Jahia/jexperience/actions/runs/12679913924/job/35340633257
> fix: prevent failure if the issue state is not defined

- .github/workflows/integration-tests.yml
- integration-tests/README.md
- integration-tests/src/jahia-reporter/testrail.ts
- integration-tests/src/main.ts
https://jira.jahia.org/browse/PIPELINE-109
Remove the unused parameter `should_skip_jahiaCIreporting` that was supposed to skip the global Testrail reporting (to the _JahiaCI_ project) but [was never set](https://github.com/search?q=org%3AJahia%20should_skip_jahiaCIreporting&type=code).
Thus that task was always running, even for PRs builds.
~~Also, collect the commands outputs (stdout and stderr) from the API calls to Testrail in the logfile `artifacts/results/testrail.log`.~~ --> idea got dropped as credentials would be leaked in the log in this case (as the executed command is present in the log file as it seems to be because of a low-level library).
Lastly, remove from the README the command upgrading Yarn (`yarn set version stable`) as this is causing the use of Yarn 4.6.x that leads …
>  PIPELINE-109: Remove unused testrail parameter and add logging for testrail API call

- .github/workflows/integration-tests.yml
It indeed corresponds to the version used here:
https://github.com/s4u/setup-maven-action/blob/a37cecafbf1e8d86c1c93d51054a63e228b96b3e/action.yml#L136-L137
v1.18.0 contains a more recent version
> Updated the version of the maven action following a deprecated notice in GitHub UI

- .github/workflows/reusable-delivery-issue-chores.yml
There is a rule in the jira instance preventing remote icons from being rendered.
> fix: updated issue icons

- build-step-npm/action.yml
Update the the building of NPM modules to use `dist/package.tgz` for the file path of the generated tgz file.
If not found, use the previous location (`dist/<<project>>-v<<version>>.tgz`).
This change is needed to accommodate the changes in https://github.com/Jahia/javascript-modules/pull/44/files and https://github.com/Jahia/luxe-jahia-demo/pull/178 where the _@jahia/scripts_ is removed from the projects' dependencies and the packing is directly handled by a `yarn pack`.
Also remove the _"Package the module"_ step as it duplicates the [_"Build the module"_](https://github.com/Jahia/jahia-modules-action/compare/update-packing-in-npm-builds?expand=1#diff-4e55c9e14c9b10e4e717c27cb494bb4e506b1ebc4641d0d8df4cded6017d20ccR66) one, that already performs a `yarn build`.
> ci(npm): Update bundling of NPM modules

- build-step-npm/action.yml
- publish-npm/action.yml
Once the NPM package has been bundled in `dist/package.tgz`, rename it to `<module name>-v<version>.tgz` and move it to `target/`, as the CI expects the generated files to follow those rules.
> ci(npm): Rename package.tgz after packing

- publish-javascript/action.yml
Rename the action from `publish-javascript-module-to-maven-repository` to  `publish-javascript` to match what's defined in the generic [`publish` action](https://github.com/Jahia/jahia-modules-action/blob/4f38a88bd8220a2d4f89f6835d61965febfd0dee/publish/action.yml#L81) and referenced by JavaScript projects (ex: https://github.com/Jahia/npm-templates-web-blue/blob/chore/rename-npm-to-javascript/.github/workflows/on-code-change.yml#L35).
Follows https://github.com/Jahia/jahia-modules-action/pull/205.
> fix: rename JavaScript publication action

- .github/workflows/reusable-delivery-issue-chores.yml
By default, the lib calling Jira is targetting the "agile" endpoints, that do not seem to be available with Jira JSM.
I verified locally that the operations for creating Jira links are still working with the rest API (not the Agile one we were using previously).
> fix: Fixed creation of jira links following migration to JSM

- .github/workflows/reusable-delivery-issue-chores.yml
Some of the jobs within an action do trigger secondary workflow runs.
For example, if a user adds the label "refresh", jahia-ci will remove it once the operation is performed, but its removal does trigger un unnecessary workflow run ("jahia-ci removing the label").
There shouldn't be a need for the issue chore workflow to be triggered by jahia-ci.
> fix: limit unnecessary github actions runs on issues chores

- release/action.yml
Store the NPM auth token in the `~/.yarnrc.yml` to allow publication of npm packages to https://registry.npmjs.org with a `yarn npm publish`.
This fixes the following error:
```
[INFO] [INFO] ➤ YN0033: No authentication configured for request
[INFO] [INFO] ➤ YN0000: Failed with errors in 0s 369ms
```
(See https://github.com/Jahia/javascript-modules/actions/runs/13546517850/job/37859375125 for full details).
Suggestion from https://github.com/actions/setup-node/issues/942#issuecomment-1920476219.
> build: Setup .yarnrc.yml to support publication with 'yarn npm publish'

- sonar-analysis/action.yml
Compatibility issues with the NVD API lead to failing nightly checks.
Fix is to do the mandatory update of dependency-check-maven and follow advise on: https://github.com/dependency-check/DependencyCheck/issues/7463
> fix: Failed to parse NVD data

- .github/workflows/release.yml
- README.md
As mentioned in the source issue, the release of the alias appears to be confusing.
With this change, we'll be able to release the action the same way we release modules and not have to worry about the creation of the alias.
This was tested here: https://github.com/Jahia/test-repo-action-release/actions/runs/13568032665/job/37925581656
A message will be automatically posted to #team-product-cicd when the tag is created.
This workflow is actually in use at GitHub, for example by the setup-node action: https://github.com/actions/setup-node/blob/main/.github/workflows/release-new-action-version.yml
> feat: Add the ability to release the action from GitHub UI

- release/action.yml
When retrieving the SBOM artifacts, include the default output directory `cyclonedx` of the [Rollup plugin](https://github.com/janbiasi/rollup-plugin-sbom), that is now used by Vite's configuration of the [Javascript Modules Engine](https://github.com/Jahia/javascript-modules/blob/main/javascript-modules-engine/rollup.config.mjs#L34).
Directory structure of `javascript-modules-engine` after a build:
Without it, the _SBOM processing_ step of the release fails (see [this example](https://github.com/Jahia/javascript-modules/actions/runs/13625915794/job/38084205392)).
> ci(sbom): Include default dir of Rollup SB0M plugin

- .github/workflows/reusable-delivery-issue-chores.yml
- .github/workflows/reusable-delivery-pr-chores.yml
- .github/workflows/reusable-integration-tests.yml
- .github/workflows/reusable-release-module.yml
- .github/workflows/reusable-sonar-scan.yml
I felt the longer we wait the more confusing it will become.
Thus prefixing all re-usable workflows with the `reusable-` prefix
> chore: re-roganized the re-usable workflows

- .github/workflows/reusable-delivery-issue-chores.yml
Aims at fixing this error:
```
[Invalid workflow file: .github/workflows/delivery-issue-chores.yml#L11](https://github.com/Jahia/jahia-private/actions/runs/13758966450/workflow)
The workflow is not valid. In .github/workflows/delivery-issue-chores.yml (Line: 11, Col: 11): Error from called workflow Jahia/jahia-modules-action/.github/workflows/reusable-delivery-issue-chores.yml@v2 (Line: 73, Col: 13): Unexpected symbol: 'and'. Located at position 46 within expression: steps.get-issue.outputs.issue_type == 'Epic' and context.payload.action == 'opened'
```
> fix: Corrected typo in workflow

- .github/workflows/reusable-delivery-issue-chores.yml
Aims at fixing this error:
```
[Invalid workflow file: .github/workflows/delivery-issue-chores.yml#L11](https://github.com/Jahia/jahia-private/actions/runs/13758966450/workflow)
The workflow is not valid. In .github/workflows/delivery-issue-chores.yml (Line: 11, Col: 11): Error from called workflow Jahia/jahia-modules-action/.github/workflows/reusable-delivery-issue-chores.yml@v2 (Line: 73, Col: 13): Unrecognized named-value: 'context'. Located at position 49 within expression: steps.get-issue.outputs.issue_type == 'Epic' && context.payload.action == 'opened'
```
> fix: Corrected typo in issues workflow

- build-step-mvn/action.yml
Include artifacts in the `target/` folders, regardless of their depth level. Needed by https://github.com/Jahia/javascript-modules/pull/217.
This is for instance needed when a module is located in a sub-sub-directory (example [here](https://github.com/Jahia/javascript-modules/blob/refacto-tests-modules/samples/hydrogen/pom.xml)).
> fix: Archive artifacts in target/ recursively

- .github/workflows/reusable-delivery-issue-chores.yml
For some reason, participants count take longer to transfer, this was making the transfer check fail.
Updated to use the assignees count, which appears to be closer to the actual issue model.
> fix: updated the transfer issue action to address an issue with participants

- .github/workflows/reusable-integration-tests.yml
- .github/workflows/reusable-sonar-scan.yml
- .gitignore
- Add missing required `github_slug` in sonar action reusable workflow
- Remove deprecated param  `should_use_build_artifacts` in reusable integration test workflow (not sure if ok to fully remove that param or keep for now) 
> [!TIP]
> fix: Fix missing/deprecated params

- publish/action.yml
- release/action.yml
The Maven repository is not cached for the Publish and Release workflows in Github: the Docker containers are running with the root user which populates the `/root/.m2/repository` Maven repository. However, `~`, refers to the user running the Github Actions, which is not the root user.
Example in [this post run jahia/jahia-modules-action/publish@v2](https://github.com/Jahia/cloudimage/actions/runs/14472671763/job/40590750314): 
```
Post job cleanup.
/usr/bin/docker exec  6fbf54684523e0c08963e69c44d3b[1](https://github.com/Jahia/cloudimage/actions/runs/14472671763/job/40590750314#step:8:1)921942ee5ff069d199c4fc49f06300ff[2](https://github.com/Jahia/cloudimage/actions/runs/14472671763/job/40590750314#step:8:2)7 sh -c "cat /etc/*release | grep ^ID"
Warning: Path Validation Error: Path(s) …
```
> ci(cache): Fix Maven cache for publish & release actions

- .github/workflows/reusable-delivery-issue-chores.yml
This update should make the issue transfer workflow more robust and easier to debug in case of failure.
> chore: updated to actions-transfer-issue v1.3.0

- .github/workflows/reusable-sonar-scan.yml
- sonar-analysis/action.yml
Causing some issues with runs because of the required status e.g. https://github.com/Jahia/graphql-core/actions/runs/14484473053
Will supply default slug in the action and remove required clause in both action and reusable workflow
- Added `steps.vars.outputs.github_slug` that defaults to `${{ github.repository }}` value if `inputs.github_slug` is not specified when calling the action.
- Existing output variable `steps.extract_branch.outputs.branch` renamed to `steps.**vars**.outputs.branch`
> [!TIP]
> fix: Add default value for sonar input

- .github/workflows/reusable-delivery-issue-chores.yml
We previously had a workflow that was re-opening issues that were closed but not in the Done column. This was put in place to prevent issues from being closed automatically when an attached PR was closed as well.
GitHub finally introduced a feature to disable that behavior, closing a PR will not automatically close associated issues.
https://github.blog/changelog/2025-04-23-users-can-now-choose-whether-merging-linked-pull-requests-automatically-closes-the-issue/
The new setting was enabled on all Jahia product repositories, the workflow can now be removed.
Some notes:
- I did not remove the actual action since it might be useful for other uses later.
- I also removed entirely the "general" job. The last remaining step was only useful to display some debug details, I moved them to the …
> feat: remove the CI job re-opening issues

- publish/action.yml
The _publish module_ step of the _On merge to main_ workflow has been failing for the [Javascript Modules repository](https://github.com/Jahia/javascript-modules/actions/workflows/on-merge.yml) with the following error ([example of a run that failed](https://github.com/Jahia/javascript-modules/actions/runs/14834286594/job/41643407422)):
```
Run EXTRACTED_NEXUS_ARTIFACT_URL=`grep -e "Uploaded.*\.jar" mvnLogs.txt | grep -v sources | sed -e 's/.*\(https.*.jar\).*/\1/g'`
grep: mvnLogs.txt: binary file matches
Error: Process completed with exit code 1.
```
However, the warning `grep: mvnLogs.txt: binary file matches` has been present for a while, and was not causing the workflow to fail (this [successful run](https://github.com/Jahia/javascript-modules/actions/runs/14833993968/job/41642569577) …
> ci: Unable to extract URLs from Maven logs

- upload-artifact/action.yml
This will make it possible to upload artifacts to a path and keep overwriting across multiple runs (i.e. have a fixed URL to point to the latest version of an artifact).
Change done to make it easy to upload the delivery report.
> feat: added the ability to upload artifacts with unlimited retention.

- release-javascript/action.yml
- release/action.yml
When the GitHub Actions were first created, a process was put in place to upload, if present CHANGELOG.md file to the GitHub Release artifacts.
In ~January 2025, GitHub uploaded the version of curl in their default runner from `7.81.0` to `8.5.0` when they switched from Ubuntu [22.04](https://github.com/actions/runner-images/blob/ubuntu24/20250427.1/images/ubuntu/Ubuntu2204-Readme.md) to [24.04](https://github.com/actions/runner-images/blob/ubuntu24/20250427.1/images/ubuntu/Ubuntu2404-Readme.md). That new version of curl is going to return an exit code 26 if it cannot find the CHANGELOG.md file making the CI step/job to fail (while precedently if was failing silently with a warning).
This is then causing executions of this workflow on Ubuntu 24.04 to fail.
This has never been an issue on …
> fix: removed uploading CHANGELOG.md

- release-javascript/action.yml
the release workflow had this steps
```
```
That was switching the origin from SSH to HTTPS
That step might have been required at a time (it wasn't possible to get to the history when it has been added) but is not required anymore.
Removing this step fixes the release workflow
If we need at a time to use the `https` connection, please refer to the [github documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#https) to do the setup
> fix: Enable release workflow commits to release branch

- .github/workflows/reusable-release-module.yml
- release/action.yml
Update the Jahia module signature that may become invalid if the release version differs from the version specified in the POM. For example, releasing version 1.2.3 when the POM contains 1.3.0-SNAPSHOT.
The change is to update the signature right after setting the POM files to the version being released.
> [!TIP]
> fix: update signature after release:prepare

- .github/workflows/reusable-release-module.yml
- release/action.yml
Fix following the change in https://github.com/Jahia/jahia-modules-action/pull/278.
`git add **/pom.xml` does not behave the same in bash (used by the CI) and zsh (used locally when testing).
Because of that, the root `pom.xml` file was not correctly added in the commit updating the signature ([this commit](https://github.com/Jahia/luxe-jahia-demo/commit/1e0c2a2562865354292e14ca33d2425e80422353) for instance).
> [!TIP]
> fix: missing root pom.xml when updating signature during release

- sonar-analysis/action.yml
Since September 22nd, the OSS Index (Sonatype) requires to authenticate to access their APIs: https://ossindex.sonatype.org/doc/auth-required
This is used internally by the [DependencyCheck plugin](https://github.com/dependency-check/DependencyCheck) that we use in our Sonar Analysis.
Because of that change, the analysis fails (see [this run](https://github.com/Jahia/html-filtering/actions/runs/18151032920/job/51661966242) as an example):
```
Warning:  An error occurred while analyzing '/root/.m2/repository/com/googlecode/owasp-java-html-sanitizer/owasp-java-html-sanitizer/20240325.1/owasp-java-html-sanitizer-20240325.1.jar' (Sonatype OSS Index Analyzer): Failed to request component-reports
Warning:  An error occurred while analyzing …
```
> chore: bump dependency-check-maven from 12.1.3 to 12.1.6
