Jahia/jahia-modules-action

- upload-artifact/action.yml
This command has a similar payload to Github's own but upload files to our own server.
After the upload, an annotation is added with the link to the files.
I created a manual trigger on the sandbox to be able to test: https://github.com/Jahia/sandbox/actions/runs/1849929564
> Added a command to upload artifacts

- sonar-analysis/action.yml
> Added missing artifact download in sonar job

- release-rollback/action.yml
- release/action.yml
To be align with changes done in the orb: https://github.com/Jahia/jahia-modules-orb/pull/104/files
> Avoid tag deletion to conflic with potential branches

- build/action.yml
- publish/action.yml
- release-rollback/action.yml
- release/action.yml
- sonar-analysis/action.yml
- Adding the m2 folder
- Removed progress indicator in maven
> Improved the use of maven

- upload-bastion/action.yml
This action was created to facilitate pushing data to Jahia server through the bastion.
> Action to upload data to Jahia server over Jahia's bastion

- build/action.yml
- generate-changelog/action.yml
- release/action.yml
- sonar-analysis/action.yml
> Added a parameter for artifact retention

- download-bastion/action.yml
https://jira.jahia.org/browse/TECH-548
Create an action to download data via the bastion
> TECH-548 - Add download-bastion action

- sonar-analysis/action.yml
- Using an environment variable for shared parameters
- spitting sonar and OWASP in two different steps
> First pass on improving sonar

- docker-tags/action.yml
> BACKLOG-19964: Fixed handling of credentials for token generation

- docker-tags/action.yml
This workflow can be used to validate https://github.com/Jahia/sandbox/actions/workflows/manual-tag.yml
> BACKLOG-19964: Fix tag condition

- release-rollback/action.yml
https://jira.jahia.org/browse/TECH-1008
> TECH-1008 - Replace actions steps by notice for removing its usage

- dependencies-check-java/action.yml
- dependencies-check-java/license-allowlist-java.txt
- dependencies-check-javascript/action.yml
- dependencies-check-javascript/license-allowlist-javascript.txt
- dependencies-get-new-versions-java/action.yml
- dependencies-get-new-versions-javascript/action.yml
- dependencies-get-unused-java/action.yml
- dependencies-get-unused-javascript/action.yml
https://jira.jahia.org/browse/TECH-1022
> TECH-1022 - Add new actions for dependencies checks

- publish/action.yml
https://jira.jahia.org/browse/TECH-1028
> TECH-1028: Add direct link to download the artifact from nexus

- publish/action.yml
https://jira.jahia.org/browse/TECH 1028
> TECH 1028: add direct link to download artifact from nexus

- build/action.yml
- generate-changelog/action.yml
- publish/action.yml
- release/action.yml
- sonar-analysis/action.yml
- static-analysis/action.yml
- upload-artifact/action.yml
https://jira.jahia.org/browse/TECH-1035
> TECH-1035: Address deprecation

- docker-images-cleanup/action.yml
https://jira.jahia.org/browse/TECH-986
> TECH-986 - Create actions for the Docker images cleanup

- docker-images-cleanup/action.yml
https://jira.jahia.org/browse/TECH-986
> TECH-986 - Remove useless login step and fix typo

- docker-images-cleanup/action.yml
https://jira.jahia.org/browse/TECH-986
"Deleting a currently tagged image deletes the tag from the repository." (https://docs.docker.com/docker-hub/api/latest/#tag/images/operation/PostNamespacesDeleteImages)
Tested here: https://github.com/Jahia/jahia-ee/actions/runs/3640581786/jobs/6145447400
> TECH-986 - Add step to remove inactive tags

- dependencies-check-java/action.yml
- dependencies-get-new-versions-java/action.yml
- dependencies-get-unused-java/action.yml
https://jira.jahia.org/browse/TECH-1040
> TECH-1040 - Add new param to use a different root folder for maven checks

- code-signer/action.yml
- docker-tags/action.yml
- download-bastion/action.yml
- generate-changelog/action.yml
- slack-jahia/action.yml
- upload-artifact/action.yml
- upload-bastion/action.yml
https://jira.jahia.org/browse/BACKLOG-20533
Update all deprecated steps
> BACKLOG-20533 Update deprecated steps

- code-signer/action.yml
- download-bastion/action.yml
- upload-artifact/action.yml
- upload-bastion/action.yml
> fix ssh-agent version

- dependencies-check-javascript/action.yml
https://jira.jahia.org/browse/TECH-1023
> TECH-1023 - Add possibility to check into subfolder

- README.md
- dependencies-get-new-versions-java/action.yml
- dependencies-get-new-versions-java/versions-maven-rules.xml
- dependencies-get-unused-java/action.yml
- dependencies-get-unused-javascript/action.yml
https://jira.jahia.org/browse/TECH-1064
> TECH-1064 - Add versions rules and missing usages of the root folder parameter

- build/action.yml
Fix artefacts used by Sonarqube.
> Fix artefacts

- integration-tests/action.yml
Adding a similar logic to what is done for v2 of the action
> Added a step to clean previous docker containers

- docker-images-cleanup/action.yml
https://jira.jahia.org/browse/TECH-1168
Solution found here: https://stackoverflow.com/questions/54794749/jq-error-at-stdin0-cannot-iterate-over-null-null
Tested here: https://github.com/Jahia/jahia-ee/actions/runs/4304735221/jobs/7506180442
> TECH-1168 - Catch error "Cannot iterate over null (null)"

- publish/action.yml
use Wagon transport for maven deploy for maven 3.9.0 compatibility
> fix maven 3.9.0 compatibility

- sonar-analysis/action.yml
> TECH-1134: Display current branch to help with debugging

- sonar-analysis/action.yml
https://jira.jahia.org/browse/TECH-1019
Change the order of steps to see if OWASP report will again be sent to Sonarqube.
> TECH-1019: Change order of checks - OWASP first

- docker-tags/action.yml
https://jira.jahia.org/browse/BACKLOG-20934
> BACKLOG-20934 - Remove latest tag

- sonar-analysis/action.yml
https://jira.jahia.org/browse/TECH-1260
Provide OWASP dependency check suppressionFiles - our own and the global one from OWASP
> TECH-1260: OWASP dependency check suppressionFiles

- sonar-analysis/action.yml
https://jira.jahia.org/browse/TECH-1260
Change url of our suppression file
- remove the global as it is already always used internally
> TECH-1260: Change url of our suppression file

- static-analysis/action.yml
> Adding quotes to prevent step from being skipped

- build-npm/action.yml
- publish-npm/action.yml
- release-npm/action.yml
- sbom-processing/action.yml
TECH-1019: Remove temporary logging of api-key
TECH-1019: Remove filtering duplicates
TECH-1019: ignore sbom artifacts under /target/checkout/
TECH-1019: Rename sbom-handling to sbom-processing
add build and release npm
add required inputs
add package.json infos
fix typo
fix typo
fix typo
fix typo
Add publish action
fix jq comand
fix fileName
add groupId from package.json
add use of maven.settings.xml
add -s to the maven deploy
add params
update params name
add debug options to maven command
add -snapshot to artifact id
add -SNAPSHOT to artifact id
add -SNAPSHOT to artifact id
add -SNAPSHOT to version
remove debug options
add release action
update git authentication
debug
remove --global from the command
small fix
small fix
fix typo
fix typo
fix typo
fix typo
split build
fix typo
add …
> BACKLOG-21129, TECH-1019 Squashed

- code-signer/action.yml
https://jira.jahia.org/browse/TECH-1403
> TECH-1403 - Update code sign commands

- dependencies-get-unused-java/action.yml
https://jira.jahia.org/browse/TECH-1490
> TECH-1490 - Update path to generated report

- build-npm/action.yml
- build/action.yml
- publish-npm/action.yml
- publish/action.yml
> Fixed a typo in the input name

- integration-tests/README.md
Just noticed that styling was off, here's a fix.
> Fixed typo in the integration-tests readme

- release/action.yml
> Prevent pom.xml.versionsBackup from being added to the git tag

- build-step-npm/action.yml
- build/action.yml
https://jira.jahia.org/browse/QA-15060 
update action build-step-npm to allow @ and /
> QA-15060: update action build-step-npm to allow @ and /

- build-npm/action.yml
- build-step-npm/action.yml
- build/action.yml
https://jira.jahia.org/browse/BACKLOG-21836
update build-step-npm to remove @borales/actions-yarn usage
> BACKLOG-21836 update build-step-npm to remove @borales/actions-yarn usage

- dependencies-check-java/action.yml
https://jira.jahia.org/browse/TECH-1632
Use the right cache and path to do the license check
> TECH-1632: Use Maven cache generated from build job

- slack-jahia/action.yml
https://jira.jahia.org/browse/SEC-71
Use latest version (v8) which contains the vulnerability fix
> SEC-71: Update tj-actions/branch-names version

- sonar-analysis/action.yml
https://jira.jahia.org/browse/TECH-1661
Make nvd_apikey a  conditional input parameter
> TECH-1661: Make nvd_apikey a conditional parameter

- integration-tests/action.yml
https://jira.jahia.org/browse/TECH-1657
See the title
> TECH-1657: Set default jahia image to jahia-ee

- build-step-mvn/action.yml
- build-step-npm/action.yml
- build/action.yml
- dependencies-check-java/action.yml
- dependencies-get-new-versions-java/action.yml
- dependencies-get-unused-java/action.yml
- generate-changelog/action.yml
- helper/action.yml
- integration-tests/action.yml
- publish/action.yml
- release-npm/action.yml
- release/action.yml
- sbom-processing/action.yml
- sonar-analysis/action.yml
- static-analysis/action.yml
- upload-artifact/action.yml
https://jira.jahia.org/browse/TECH-1639
upgrade actions
> TECH-1639 upgrade actions

- build-step-mvn/action.yml
- build-step-npm/action.yml
- build/action.yml
- integration-tests/action.yml
- integration-tests/src/main.ts
The recent changes were hitting one of the breaking changes documented here (uploading with the same artifact name): https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
> TECH-1639: Prevent two artifacts with the same name to be uploaded

- build-step-npm/action.yml
https://jira.jahia.org/browse/TECH-1270
Archive bom files in build-artifacts for npm build
> TECH-1270: Also archive bom files in build-artifacts for npm build

- sonar-analysis/action.yml
https://jira.jahia.org/browse/TECH-1872
See https://github.com/jeremylong/Open-Vulnerability-Project/tree/main/vulnz#api-key-is-used-and-a-403-or-404-error-occurs and https://github.com/jeremylong/DependencyCheck/issues/6834
> TECH-1872: Update dependency-check version to 10.0.3

- release/action.yml
Add all modified files when updating test module version
> fix test modules update

- sonar-analysis/action.yml
Disabling yarn audit as it causes issues in our pipeline.
https://github.com/jeremylong/DependencyCheck/issues/4215
https://github.com/jeremylong/DependencyCheck/issues/4894
https://github.com/jeremylong/DependencyCheck/issues/6325
> PIPELINE-76: Disable yarn audit

- .github/workflows/sonar-scan.yml
> PIPELINE-76: Removed unnecessary parameter

- .github/workflows/release-module.yml
https://jira.jahia.org/browse/PIPELINE-79
> PIPELINE-79: Implement re-usable workflow for module releases

- code-signer/action.yml
https://jira.jahia.org/browse/PIPELINE-91
See discussion in [#jahia-code-signing-issue](https://jahia.slack.com/archives/C07SZ90TF3Q)
> PIPELINE-91: Remove quotes that corrupts the code signing

- .github/workflows/issues-chores.yml
Update the issues chores workflow to add issues to projects based on labels
> Attach issues to projects based on labels

- .github/workflows/issues-chores.yml
See description in https://github.com/Jahia/jahia-private/issues/2269
> Added new action to create links to GitHub issues from Jira

- code-signer/action.yml
https://jira.jahia.org/browse/PIPELINE-105
Some minor tweaks/improvements:
- Explicitly use java 11 version to make sure we use a compatible version of java for code signing.
- Add --verbose logging to sign4j
> PIPELINE-105: code signing improvements

- code-signer/action.yml
https://jira.jahia.org/browse/PIPELINE-105
> PIPELINE-105: Add a step to display certificate data

- .github/workflows/reusable-delivery-issue-chores.yml
Following creation of these credentials by @mburel
> chore: updated the secrets to the ones newly created

- .github/workflows/reusable-delivery-issue-chores.yml
- delivery/create-security-ticket/action.yml
Create a security ticket for every new Epic created and added to the Product Team project (https://github.com/Jahia/jahia-modules-action/blob/3421-security-for-epic/.github/workflows/reusable-delivery-issue-chores.yml#L64 needs to be updated)
> feat(ci): create a security for every new epic

- .github/workflows/reusable-delivery-issue-chores.yml
To be merged once we begin using the common "Product Team" project.
> feat: updated project ID to the product team project

- .github/workflows/reusable-delivery-issue-chores.yml
https://github.com/Fgerthoffert/actions-transfer-issue/pull/18
> feat: improved robustness of issue transfer

- delivery/add-project-based-on-milestone/action.yml
This should correct this error: https://github.com/Jahia/visibility/actions/runs/13929303523/job/38982099304
> fix: handle the case when no projects are attached to an issue

- .github/workflows/reusable-release-module.yml
- release/action.yml
To prevent any breakage when a module is not yet using the reusable release workflow
> [!TIP]
> fix: Set GPG parameters as not required

- .github/workflows/reusable-on-code-change.yml
> feat: Add reusable workflow on code change

- release/action.yml
> chore: added curl version to ease debugging of the release action

- integration-tests/action.yml
- integration-tests/dist/licenses.txt
- integration-tests/src/docker/login.ts
- integration-tests/src/main.ts
In the context of https://github.com/Jahia/jahia-private/issues/4180, we need to introduce support for multiple Docker registries.
To facilitate the transition phase (at some point, the action will be used by repositories still using docker hub for private repos, while other will be using the github registry), I introduced a new variable for registries. At a later stage, we would remove docker_username and docker_password parameters and use only docker_registries.
Passing the array of registries would be done like this (thanks Copilot): 
```
- name: Run Integration Tests
uses: ./integration-tests
with:
docker_registries: |
[
{
"registry": "ghcr.io",
"username": "${{ github.actor }}",
"password": "${{ secrets.GITHUB_TOKEN }}"
},
{
"registry": "my-private-registry.com",
"username": "${{ …
```
> feat: added support for login to multiple Docker registries

- sonar-analysis/action.yml
Bump sonar and dependency-check maven plugin versions
> [!TIP]
> chore: bump sonar and dependency-check maven plugin versions
